name: 'SweetBlue Deploy WIKI'

on:

  workflow_dispatch:
    inputs:
      bumpVersion: 'Bump the markdown files with the current version in build.gradle'
      required: false
      default: true

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Update Documentation
        run: ./gradlew bumpMarkdown

      - name: Deploy markdown to wiki
        uses: SwiftDocOrg/github-wiki-publish-action@v1
        with:
          path: "markdown"
        env:
          GH_PERSONAL_ACCESS_TOKEN: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}