name: 'SweetBlue Deploy WIKI'

on:
  # TODO - Remove the pages_deploy branch before merging into dev!
  push:
    branches: [ main, 4.0/pages_deploy ]

  workflow_dispatch:

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

#      - name: Update Documentation
#        run: ./gradlew bumpMarkdown

      - name: Deploy markdown to wiki
        uses: SwiftDocOrg/github-wiki-publish-action@v1
        with:
          path: "markdown"
        env:
          GH_PERSONAL_ACCESS_TOKEN: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}