name: 'SweetBlue Pages Deploy'

on:
  push:
    branches: [ main ]

  workflow_dispatch:


permissions: write-all

jobs:
  PublishPages:
    runs-on: ubuntu-latest
    environment:
      name: Release

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # Generate javadoc again to make sure it's current
      - name: Generate javadoc
        run: ./gradlew gendocs

      # Replace javadoc folder with the latest docs just generated
      - name: Replace javadocs
        run: |
          rm -rf javadocs/
          cp -r docs/* javadocs/

      - name: Commit
        uses: EndBug/add-and-commit@v9
        with:
          add: '-u'
          message: 'Updated javadocs folder'

      # Publish to github pages
      - name: Publish to Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: docs