name: 'SweetBlue Pages Deploy'

on:
  push:
    # TODO - Remove the pages_deploy branch before merging into dev!
    branches: [ main, 4.0/pages_deploy ]

  workflow_dispatch:


permissions: write-all

jobs:
  PublishPages:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # Generate javadoc again to make sure it's current
      - name: Generate javadoc
        run: ./gradlew gendocs

      # Replace javadoc folder with the latest docs just generated
      - name: Replace javadocs
        run: |
          rm -rf javadocs/
          mkdir javadocs/
          cp -r docs/* javadocs/
          # TODO - This is for testing, remove before merge!
          ls javadocs/

      - name: Commit
        uses: EndBug/add-and-commit@v9
        with:
          add: '-u'
          message: 'Updated javadocs folder'
