name: 'SweetBlue Snapshot Deployment'

on:

  workflow_dispatch:

jobs:
  PreBuild:
    runs-on: ubuntu-latest
    outputs:
      snapshot_verified: ${{ steps.check_snapshot.outputs.is_snapshot }}

    steps:
      - uses: actions/checkout@v3

      - name: Install Java 17
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Write version file
        run: ./gradlew writeVersionFile

      - name: Verify Snapshot
        id: check_snapshot
        run: |
          number=(cat version.txt | grep -c "\-SNAPSHOT")
          if [ "$number" ge 1 ]
          then
            echo true >> "$GITHUB_OUTPUT"
          else
            echo false >> "$GITHUB_OUTPUT"
          fi

  Build:
    runs-on: ubuntu-latest
    # Using the release environment for this step will force a manual approval in github
    # before it can proceed
    environment:
      name: Snapshot

    needs: PreBuild
    if: needs.PreBuild.outputs.snapshot_verified

    steps:
      - uses: actions/checkout@v3

      - name: Install Java 17
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Build Library And Sample Apps
        run: ./gradlew assembleRelease

  Deploy:
    runs-on: ubuntu-latest
    # Using the release environment for this step will force a manual approval in github
    # before it can proceed
    environment:
      name: Snapshot

    needs: Build
    steps:
      - uses: actions/checkout@v3

      - name: Install Java 17
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      # Now build the artifacts, and javadocs jars, and publish to Azure Artifacts
      - name: Deploy to Azure
        env:
          AZURE_ARTIFACTS_ENV_ACCESS_TOKEN: ${{ secrets.AZURE_ARTIFACTS_ENV_ACCESS_TOKEN }}
        run: ./gradlew assembleRelease sbjavadocJar publish
