name: 'SweetBlue Snapshot Deployment'

on:

  workflow_dispatch:
    inputs:
      snapshot_version:
        description: 'Additional version number to tack onto the snapshot version (eg 4.0.1 version, if you supply the snapshot version of 3, the version will end up as 4.0.1.3-SNAPSHOT'
        required: false
        default: ''

jobs:
  TheTest:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install Java 17
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Test out things
        run: |
          ./gradlew writeVersionFile -PuseSnapshot=${{ github.events.inputs.snapshot_version }}
          cat version.txt
#  Build:
#    runs-on: ubuntu-latest
#    # Using the release environment for this step will force a manual approval in github
#    # before it can proceed
#    environment:
#      name: Snapshot
#
#    steps:
#      - uses: actions/checkout@v3
#
#      - name: Install Java 17
#        uses: actions/setup-java@v3
#        with:
#          distribution: 'zulu'
#          java-version: '17'
#
#      - name: Build Library And Sample Apps
#        run: ./gradlew assembleRelease -PuseSnapshot=${{ github.event.inputs.snapshot_version }}
#
#  Deploy:
#    runs-on: ubuntu-latest
#    # Using the release environment for this step will force a manual approval in github
#    # before it can proceed
#    environment:
#      name: Snapshot
#
#    needs: Build
#    steps:
#      - uses: actions/checkout@v3
#
#      - name: Install Java 17
#        uses: actions/setup-java@v3
#        with:
#          distribution: 'zulu'
#          java-version: '17'
#
#      # Now build the artifacts, and javadocs jars, and publish to Azure Artifacts
#      - name: Deploy to Azure
#        env:
#          AZURE_ARTIFACTS_ENV_ACCESS_TOKEN: ${{ secrets.AZURE_ARTIFACTS_ENV_ACCESS_TOKEN }}
#        run: ./gradlew assembleRelease sbjavadocJar publish
