name: 'WikiTest'

on:

  workflow_dispatch:

jobs:
  WikiUpload:
    runs-on: ubuntu-latest

    steps:
    - name: Deploy markdown to wiki
      uses: SwiftDocOrg/github-wiki-publish-action@v1
      with:
        path: "markdown"
      env:
        GH_PERSONAL_ACCESS_TOKEN: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}